services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

        bind:
            $extension: '%env(URL_ENV)%'

    # Editorial module: body element transformers
    App\Editorial\Assembler\Apps\Body\:
        resource: '../../src/Editorial/Assembler/Apps/Body/'
        exclude:
            - '../../src/Editorial/Assembler/Apps/Body/BodyTagVideoTransformer.php'
            - '../../src/Editorial/Assembler/Apps/Body/BodyTagVideoYoutubeTransformer.php'
            - '../../src/Editorial/Assembler/Apps/Body/BodyElementTransformer.php'
            - '../../src/Editorial/Assembler/Apps/Body/BodyTransformerPipeline.php'
        tags: [ 'app.body_element_transformer' ]

    App\Editorial\Assembler\Apps\Body\BodyTagVideoTransformer:
        arguments:
            $playerHost: '%env(PLAYER_HOST)%'
        tags: [ 'app.body_element_transformer' ]

    App\Editorial\Assembler\Apps\Body\BodyTagVideoYoutubeTransformer:
        arguments:
            $playerHost: '%env(PLAYER_HOST)%'
        tags: [ 'app.body_element_transformer' ]

    App\Editorial\Assembler\Apps\Body\BodyTransformerPipeline:
        class: App\Editorial\Assembler\Apps\Body\BodyTransformerPipeline

    # Editorial module: media transformers
    App\Editorial\Assembler\Apps\Media\:
        resource: '../../src/Editorial/Assembler/Apps/Media/'
        exclude:
            - '../../src/Editorial/Assembler/Apps/Media/MediaTransformer.php'
            - '../../src/Editorial/Assembler/Apps/Media/MediaTransformerPipeline.php'
            - '../../src/Editorial/Assembler/Apps/Media/Widget/'
        tags: [ 'app.media_transformer' ]

    App\Editorial\Assembler\Apps\Media\MediaTransformerPipeline:
        class: App\Editorial\Assembler\Apps\Media\MediaTransformerPipeline

    # Editorial module: widget transformers
    App\Editorial\Assembler\Apps\Media\Widget\:
        resource: '../../src/Editorial/Assembler/Apps/Media/Widget/'
        exclude:
            - '../../src/Editorial/Assembler/Apps/Media/Widget/WidgetTypeTransformer.php'
            - '../../src/Editorial/Assembler/Apps/Media/Widget/WidgetTransformerPipeline.php'
        tags: [ 'app.widget_type_transformer' ]

    App\Editorial\Assembler\Apps\Media\Widget\WidgetTransformerPipeline:
        class: App\Editorial\Assembler\Apps\Media\Widget\WidgetTransformerPipeline

    # Wire ResponseAssemblerInterface to AppsAssembler
    App\Editorial\Assembler\ResponseAssemblerInterface: '@App\Editorial\Assembler\Apps\AppsAssembler'
